telnetd manifest tuning, testing running on reboot

diff --git a/puppet/hptelnetd/templates/telnetd.init.erb b/puppet/hptelnetd/templates/telnetd.init.erb
--- a/puppet/hptelnetd/templates/telnetd.init.erb
+++ b/puppet/hptelnetd/templates/telnetd.init.erb
@@ -15,8 +15,6 @@ NAME="telnetd"
 PYTHON=`which python`
 PIDFILE="/var/run/telnetd.pid"
 
-. /puppet/metalib/bin/lib.sh
-
 cd $BASE || exit 1
 
 killwaitpids() {
@@ -30,6 +28,20 @@ killwaitpids() {
         done
 }
 
+rreturn() {
+	RET=$1
+	MSG=$2
+	if [ $RET -eq 0 ]; then
+		echo "RESULT: OK $MSG"
+		exit 0
+	else
+		echo "RESULT: FAILED $MSG"
+		exit 1
+	fi
+
+	echo "RESULT: FAILED THIS SHOULD NOT HAPPEN $0 $@"
+	exit 1
+}
 
 case "$1" in
 
